version: '3'


services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  webserver:
    build: .
    ports: 
      - "8501:8501"
    volumes:
      - .:/code
    depends_on:
        - redis        